-- ============================================================
-- 0002: Well detail fields + Pump Catalog (Supabase / PostgreSQL)
-- ครอบคลุม 2 ฟีเจอร์ล่าสุด:
--   1) ฟิลด์เพิ่มเติมหน้า "บันทึกข้อมูลบ่อหลังเจาะ"
--      (well_strata_logs / well_pumps / well_control_boxes)
--   2) แคตตาล็อกปั๊มซับเมอร์ส (pump_catalog_models) + repair_records.pump
-- ปลอดภัยต่อการรันซ้ำ (idempotent) — paste ใน SQL Editor ได้เลย
-- ============================================================

-- ---------- 1) WELL DETAIL: เพิ่มคอลัมน์ ----------

alter table public.well_strata_logs
  add column if not exists lithology_type text;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'chk_strata_lithology_type'
  ) then
    alter table public.well_strata_logs
      add constraint chk_strata_lithology_type
      check (lithology_type in ('TOP_SOIL','CLAY','SAND','GRAVEL','LATERITE','SANDSTONE','SHALE','LIMESTONE','GRANITE','BASALT','HARDROCK','OTHER'));
  end if;
end $$;

alter table public.well_pumps
  add column if not exists pump_model          text,
  add column if not exists voltage             text,
  add column if not exists phase               integer,
  add column if not exists discharge_size_mm   numeric(6,1),
  add column if not exists rated_flow_m3hr     numeric(8,2),
  add column if not exists rated_head_m        numeric(7,2);

alter table public.well_control_boxes
  add column if not exists protection_type text,
  add column if not exists features        text;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'chk_control_box_protection'
  ) then
    alter table public.well_control_boxes
      add constraint chk_control_box_protection
      check (protection_type in ('OVERLOAD_RELAY','CIRCUIT_BREAKER','AUTO_RESTART','WATER_LEVEL','LIGHTNING','NONE','OTHER'));
  end if;
end $$;

-- ---------- 2) REPAIR: repair_records.pump (ปั๊มที่เปลี่ยน/ติดตั้ง) ----------

alter table public.repair_records
  add column if not exists pump jsonb;

-- ---------- 3) MASTER: pump_catalog_models ----------

create table if not exists public.pump_catalog_models (
  model_id        bigint generated by default as identity primary key,
  brand           text not null,
  series          text,
  model           text not null,
  bore_size       text,
  flow_rate       text,
  motor_power     text,
  phase           text,
  discharge_size  text,
  impeller_stages text,
  max_head_m      text,
  material        text,
  features        text,
  reference_price numeric(12,2),
  notes           text,
  sort_order      integer not null default 0,
  is_active       boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_pump_catalog_brand
  on public.pump_catalog_models(brand, is_active, sort_order);

drop trigger if exists trg_pump_catalog_updated on public.pump_catalog_models;
create trigger trg_pump_catalog_updated
  before update on public.pump_catalog_models
  for each row execute function public.set_updated_at();

-- ---------- 4) SEED: ข้อมูลแคตตาล็อก 38 รายการ (เฉพาะเมื่อตารางว่าง) ----------

do $$
begin
  if not exists (select 1 from public.pump_catalog_models limit 1) then

    insert into public.pump_catalog_models
      (brand, series, model, bore_size, flow_rate, motor_power, phase, discharge_size, impeller_stages, max_head_m, material, features, reference_price, notes, sort_order) values
    -- ===== Franklin Electric =====
    ('FRANKLIN', '3200 Series', '3200 Series (4")', '4', '5/7/10/15/25 gpm', '0.5-10 HP', '1/3 เฟส', '1.25" NPT', '6-44 สเตจ', 'สูงสุด ~500 ม.', 'สแตนเลส + เทอร์โมพลาสติก', 'ขนาดกะทัดรัด เส้นผ่านศูนย์กลาง 3.75" รวมสายไฟ', NULL, NULL, 1),
    ('FRANKLIN', '4400 Tri Seal Series', '4400 Tri Seal Series (4")', '4', '18/25/30/45/60/70 LPM', '0.5-7.5 HP', '1/3 เฟส', '2" BSP', 'หลายสเตจ', 'สูงสุด ~430 ม.', 'AISI 304', 'ระบบ Tri-Seal ป้องกันทราย ใบพัดแบบ floating', NULL, NULL, 2),
    ('FRANKLIN', '4400 High Capacity', '4400 High Capacity (4")', '4', '100/150/200/270 LPM', '0.75-7.5 HP', '1/3 เฟส', '2" BSP', 'หลายสเตจ', 'สูงสุด ~300 ม.', 'สแตนเลส', 'อัตราการไหลสูง เหมาะสำหรับบ่อ 4 นิ้ว', NULL, NULL, 3),
    ('FRANKLIN', '6" Tri Seal High Capacity', '6" Tri Seal High Capacity', '6', '50/75/100/125 gpm', '1.5-40 HP', '1/3 เฟส', '2" NPT', '3-44 สเตจ', 'สูงสุด ~366 ม. (1,200 ft)', 'สแตนเลส', 'สำหรับงานอัตราการไหลสูง', NULL, NULL, 4),
    ('FRANKLIN', 'SSI Series', 'SSI Series (6"/8"/10")', '6/8/10', '6-270 m³/h', '0.55-55 kW', '1/3 เฟส', 'Rp 2.5"/3"/4"/5"', '1-42 สเตจ', 'สูงสุด 377 ม.', 'AISI 304', 'ปั๊ม turbine แบบ stamped stainless steel ซ่อมบำรุงได้', NULL, NULL, 5),
    ('FRANKLIN', 'SR Series', 'SR Series (6"/8")', '6/8', 'สูงสุด 80 m³/h (50Hz)', 'สูงสุด 400 kW', '3 เฟส', 'Rp 2"-4"', 'หลายสเตจ', 'สูงสุด 700 ม. (70 Bar)', 'AISI 304/316/904L', 'รองรับอุณหภูมิสูงสุด 90°C มีเวอร์ชัน high pressure', NULL, NULL, 6),
    ('FRANKLIN', 'FS Series', 'FS Series (8"-16")', '8/10/12/14/16', '100-1,000 m³/h', 'สูงสุด 400 kW', '3 เฟส', 'หน้าแปลน (Flanged)', 'หลายสเตจ', 'สูงสุด 700 ม.', 'AISI 316', 'งานอุตสาหกรรมปริมาณน้ำมาก', NULL, NULL, 7),
    ('FRANKLIN', 'J-Class', 'J-Class (4")', '4', '5/7/10/15/20/25 gpm', '0.5-5 HP', '1/3 เฟส', '1.25" NPT', 'หลายสเตจ', 'สูงสุด ~1,600 ft', 'สแตนเลส + เทอร์โมพลาสติก', 'ซีรีส์เก่าที่ทนทาน มีแคตตาล็อกครบรุ่น', NULL, NULL, 8),
    ('FRANKLIN', 'High Capacity 4"', '100FH (High Capacity 4")', '4', '100 LPM', '0.75-7.5 HP', '1/3 เฟส', '2"', 'หลายสเตจ', 'สูงสุด ~250 ม.', 'สแตนเลส', NULL, NULL, NULL, 9),
    ('FRANKLIN', 'J-Class 4"', '100FA2S4-PEXB (J-Class)', '4', NULL, '2 HP (1,500 W)', '1 เฟส 220V', '2"', '12 ใบ', NULL, 'สแตนเลส', NULL, 26490.00, NULL, 10),
    ('FRANKLIN', 'High Capacity 4" (หัวปั๊ม)', '12AD26-75 (หัวปั๊ม)', '4', '160-260 LPM', '7.5 HP', NULL, '1.5"', '26 ใบ', '111-47 ม.', 'สแตนเลส', NULL, 10560.00, NULL, 11),
    ('FRANKLIN', 'High Capacity 4"', 'High Capacity 4" 2HP (1 เฟส)', '4', NULL, '2 HP', '1 เฟส', NULL, NULL, '~200 ม.', NULL, NULL, NULL, NULL, 12),
    ('FRANKLIN', 'High Capacity 4"', 'High Capacity 4" 2HP (3 เฟส)', '4', NULL, '2 HP', '3 เฟส', NULL, NULL, '~200 ม.', NULL, NULL, 31574.00, NULL, 13),
    ('FRANKLIN', 'High Capacity 4"', 'High Capacity 4" 3HP (1 เฟส)', '4', NULL, '3 HP', '1 เฟส', NULL, NULL, '~250 ม.', NULL, NULL, 22950.00, NULL, 14),
    ('FRANKLIN', 'High Capacity 4"', 'High Capacity 4" 3HP (3 เฟส)', '4', NULL, '3 HP', '3 เฟส', NULL, NULL, '~250 ม.', NULL, NULL, 23450.00, NULL, 15),
    ('FRANKLIN', 'มอเตอร์ 6"', 'Y DELTA มอเตอร์ 6" 20HP', '6', NULL, '20 HP', '3 เฟส 380V', NULL, NULL, NULL, NULL, 'มอเตอร์ปั๊มขนาด 6 นิ้ว แบบ Y-Delta', 105800.00, NULL, 16),

    -- ===== TORQUE (นำเข้าอิตาลี โดย SOIHA INTERGROUP) =====
    ('TORQUE', '2BM Series', '2BM Series (3")', '3', '50 LPM', '0.5-2 HP', '1/3 เฟส', NULL, '11-37 ใบ', 'สูงสุด 140 ม.', 'AISI 304', NULL, NULL, 'ขนาดบ่อ 3"/4"/6" | กำลังรวม 0.33-20 HP | ใบพัด 3-40 | อัตราไหล 50-1,200 LPM | AC 1 เฟส 220V / 3 เฟส 380V | ทนไฟ 1 เฟส 170-240V / 3 เฟส 350-380V | กันน้ำ IP68 Class F (155°C) | แรงกดเพลา 6,500 N สตาร์ท 30 ครั้ง/ชม. | รับประกัน 1 ปี (PRO SERIES 2 ปี) | มาตรฐาน FDA NEMA KTW ACS WRAS', 1),
    ('TORQUE', '2BH/2BM Series', '2BH/2BM Series (4")', '4', '2 m³/h', '0.33-1.5 HP', '1/3 เฟส', NULL, 'หลายสเตจ', NULL, 'AISI 304', NULL, NULL, NULL, 2),
    ('TORQUE', '4BH/4BM Series', '4BH/4BM Series (4")', '4', '4 m³/h', '1-3 HP', '1/3 เฟส', NULL, 'หลายสเตจ', NULL, 'AISI 304', NULL, NULL, NULL, 3),
    ('TORQUE', '6BH/6BM Series', '6BH/6BM Series (4")', '4', '6 m³/h', '1.5-5 HP', '1/3 เฟส', NULL, 'หลายสเตจ', NULL, 'AISI 304', NULL, NULL, NULL, 4),
    ('TORQUE', '8BH/8BM Series', '8BH/8BM Series (4")', '4', '8 m³/h', '3-7.5 HP', '1/3 เฟส', NULL, 'หลายสเตจ', NULL, 'AISI 304', NULL, NULL, NULL, 5),
    ('TORQUE', '12/16 BH Series', '12/16 BH Series (4")', '4', '12/16 m³/h', '5-10 HP', '1/3 เฟส', NULL, 'หลายสเตจ', NULL, 'AISI 304', NULL, NULL, NULL, 6),
    ('TORQUE', '14SP Series', '14SP Series (4")', '4', '14 m³/h', '7.5-10 HP', '1/3 เฟส', NULL, 'หลายสเตจ', NULL, 'AISI 304', NULL, NULL, NULL, 7),
    ('TORQUE', '4BG Series', '4BG Series (3.5")', '3.5', '4 m³/h', '1-3 HP', '1/3 เฟส', NULL, 'หลายสเตจ', NULL, 'AISI 304', NULL, NULL, NULL, 8),
    ('TORQUE', '30BP Series', '30BP Series (6")', '6', 'สูงสุด 1,200 LPM', '5.5-20 HP', '1/3 เฟส', '3"', '3-5 ใบ', 'สูงสุด 70 ม.', 'AISI 304', NULL, NULL, NULL, 9),
    ('TORQUE', '2BM Series', 'TQ-SP 2BM16-3/S', '3', NULL, '0.75 HP (0.55 kW)', '1 เฟส 220V', '1.25"', '16 ใบ', '64 ม.', 'AISI 304', NULL, 10406.00, 'เหมาะสำหรับบ่อลึก 37-60 ม.', 10),
    ('TORQUE', '2BM Series', 'TQ-SP 2BM20-4/ST', '4', NULL, '1.5 HP (1.1 kW)', '3 เฟส 220V', '1.5"', '20 ใบ', '130 ม.', 'AISI 304', NULL, 13915.00, 'เหมาะสำหรับบ่อลึก 53-119 ม.', 11),
    ('TORQUE', '4BM Series', 'TQ-SP 4BM09-4', '4', NULL, '1 HP', NULL, NULL, '9 ใบ', NULL, 'AISI 304', NULL, 14190.00, NULL, 12),
    ('TORQUE', '4BM Series', 'TQ-SP 4BM14-4/S', '4', NULL, '1.5 HP (1.1 kW)', '1 เฟส 220V', '1.5"', '14 ใบ', '84 ม.', 'AISI 304', NULL, 13623.00, 'ราคาโดยประมาณ ~11,800-13,623 บาท', 13),
    ('TORQUE', '4BM Series', 'TQ-SP 4BM14-4', '4', NULL, '1.5 HP (1.1 kW)', '3 เฟส 220V', '1.5"', '14 ใบ', NULL, 'AISI 304', NULL, NULL, NULL, 14),
    ('TORQUE', '6BM Series', 'TQ-SP 6BM10-4', '4', NULL, '1.5 HP', NULL, '2"', '10 ใบ', NULL, 'AISI 304', NULL, NULL, NULL, 15),
    ('TORQUE', '30BP Series', 'TQ-SP 30BP03-6', '6', NULL, '3 HP (2.2 kW)', '3 เฟส 220V', '3"', '3 ใบ', '39 ม.', 'AISI 304', NULL, NULL, NULL, 16),
    ('TORQUE', 'ปั๊มจุ่ม', 'TQ-SP-M120', NULL, '91 LPM', '100 W', '1 เฟส 220V', '3/4" - 1"', NULL, '6.5 ม.', NULL, 'ปั๊มจุ่มระบายน้ำ', NULL, NULL, 17),
    ('TORQUE', 'ปั๊มจุ่ม', 'TQ-SP-M450', NULL, '250 LPM', '450 W', '1 เฟส 220V', '2"', NULL, '12 ม.', NULL, 'ปั๊มจุ่มระบายน้ำ', NULL, NULL, 18),
    ('TORQUE', 'ปั๊มจุ่ม TDS', 'TQ-SP-TDS180', NULL, '120 LPM', '300 W (มอเตอร์ 180 W)', '1 เฟส 220V', '1"', NULL, '6 ม.', NULL, 'ปั๊มจุ่มระบายน้ำ', NULL, '2,860 rpm', 19),
    ('TORQUE', 'ปั๊มจุ่ม TDS', 'TQ-SP-TDS550F', NULL, '300 LPM', '800 W (มอเตอร์ 550 W)', '1 เฟส 220V', '2"', NULL, '10 ม.', NULL, 'ปั๊มจุ่มระบายน้ำ', NULL, '2,860 rpm', 20),
    ('TORQUE', 'ปั๊มจุ่ม TDS', 'TQ-SP-TDS750', NULL, '350 LPM', '1,000 W (มอเตอร์ 750 W)', '1 เฟส 220V', '2"', NULL, '12 ม.', NULL, 'ปั๊มจุ่มระบายน้ำ', NULL, '2,860 rpm', 21),
    ('TORQUE', 'ปั๊มโซลาร์', 'TQ-SP-4DC0806-AD-A11/S', '4', NULL, '1.5 HP (1,100 W)', '1 เฟส 220V / DC', '2"', '6 ใบ', '75 ม.', 'AISI 304', 'ปั๊มโซลาร์ รองรับไฟ AC/DC ใช้ร่วมกับโซลาร์เซลล์', NULL, NULL, 22);

  end if;
end $$;

-- ---------- 5) RLS สำหรับ pump_catalog_models (ตรงกับตารางอื่น) ----------

alter table public.pump_catalog_models enable row level security;

drop policy if exists "catalog_all" on public.pump_catalog_models;
create policy "catalog_all" on public.pump_catalog_models
  for all to authenticated
  using (public.current_user_role() in ('ADMIN','DRILLER'))
  with check (public.current_user_role() in ('ADMIN','DRILLER'));

-- ============================================================
-- END OF MIGRATION 0002
-- ============================================================
